### ISSUE TITLE
Seems like there's no item except fish

### ISSUE THREAD

**Issue by baooduy** [ExpensiveKoala/Fishing-Real#13]
I've tested a while and noticed that I couldn't get any other item from fishing, here's my latest.log:
[latest.log](https://github.com/ExpensiveKoala/Fishing-Real/files/9364572/latest.log)

**Comment by ExpensiveKoala** [comment]
Thanks for bringing this to my attention. I will try to fix this asap.

Steps to fix below (for my future reference):
It seems to be caused by https://github.com/ExpensiveKoala/Fishing-Real/blob/master/src/main/java/koala/fishingreal/FishingReal.java#L43 `.result()` when `getConversionFromStack` returns null if there is no conversion registered.
