### ISSUE TITLE
[Suggestion] Offhand Net

### ISSUE THREAD

**Issue by Ravin890** [ExpensiveKoala/Fishing-Real#2]
So while playing I was thinking it would be cool if you could add in an item like a net which if a player holds it in their offhand while fishing it would make the fish caught act as if the mod was not enabled or fill buckets of water with the fish to make fishing in the middle of the water viable.

**Comment by ExpensiveKoala** [comment]
A new item would definitely be out of scope for this mod, but the water bucket suggestion is something to consider.

Although, I'm not sure how much I like that idea. While it does make sense to have that as it is currently near impossible to fish on a boat in the middle of a large body of water.

Unfortunately, much like there is no easy way to convert item->entity there is no easy way to convert item->bucketed fish. It would quite nearly double the complexity of the mod. Requiring a whole json datapack for the item->bucketed fish conversion as well.

Because of this, regretfully, I will have to say no to this suggestion.

**Comment by MarioSMB** [comment]
Pardon the revival - I may not be an expert in Minecraft modding, but wouldn't it be possible to simply try a use action on the fished up entity after performing the item->entity replacement when the player has a bucket of water in their off-hand?  
It depends on whether you consider this feature out of scope of your mod, but that may be a way to support the "net" feature with any (even modded) fish.

**Comment by ExpensiveKoala** [comment]
I've added this, but in playtesting it felt kinda op... so it's disabled by default and added as a config option.
