### ISSUE TITLE
Compat issue with Quality Crops

### ISSUE THREAD

**Issue by CanecaKun** [ExpensiveKoala/Fishing-Real#27]
When both mods are installed, more frequently only quality crops "fish item" is fished instead of the proper fish entity
(Mod does not work properly)

**Comment by ExpensiveKoala** [comment]
Are you using a datapack or compatability mod that adds compatibility with Quality Crops?
There is no way to dynamically figure out which mob corresponds with a specific item, so using a datapack that adds this conversion is required. If [making your own datapack](https://minecraft.wiki/w/Tutorials/Creating_a_data_pack), you'd make them like below.
```json
{
  "input": {
    "item": "qualitycrops:cod_iron"
  },
  "result": {
    "id": "minecraft:cod"
  }
}
```

Alternatively, since it seems Quality Crops adds their iron/gold/diamond versions to both the fishing loot table and entity drops. You could simply override the fishing loot table or delete their fishing loot table override.

**Comment by ExpensiveKoala** [comment]
A few of the bigger modpacks that included my mod have their data packs public. I don't remember which version, but Enigmatica has my mod. 

Also, I have a data pack for aquaculture compat that you can copy the structure of: https://www.curseforge.com/minecraft/customization/fishing-real-aquaculture-datapack
